#!/usr/bin/env sh

set -eu
# set -o pipefail

usage() {
        cat <<'EOF'
Usage: ripper [-v]
       ripper -h

Extract tracs from cds, convert them to .mp3 (and enumerate them)

Options:
  -h, --help      Print this message and exit
  -v, --verbose   Be verbose
  -d, --digits    Set the expected number of digits (default=2)


Old Audio books are often spread across multiple cds
this utility streamlines combining them together
Notes:
  - it uses `sha256sum` to detect if cd has been changed

EOF
}


PARSED_OPTIONS=$(getopt -o hvd --long help,verbose,digits -- "$@")
eval set -- "$PARSED_OPTIONS"

DIGITS=2
while true; do
        case "$1" in
        -h|--help) usage; exit 0;;
        -v|--verbose) set -x; shift;;
        -d|--digits) DIGITS=$2; shift 2;;
        --) shift; break;;
        *) echo "Unknown option $1" >&2; usage >&2; exit 1;;
        esac
done

shift $((OPTIND-1))

LAST_TRACK_NO=0
LAST_CD_HASH=""

is_new_cd_loaded() {
    cdparanoia -Q &> /dev/null || return 1
    local HASH=$(cdparanoia -Q |& sha256sum)
    export LAST_CD_HASH="$HASH"
}

wait_new_cd() {
    while true; do
        is_new_cd_loaded && return 0
        echo "Waiting for new cd to be loaded. Or use Ctrl-C to exit"
        sleep 30;
    done
}

load_cd() {
    local tmp_dir=$(mktemp -d)
    cd "$tmp_dir"
    cdparanoia -B
    echo $tmp_dir
}

format_track_name() {
    local track_no=$1
    local track_no_formated=$(printf "%0${DIGITS}d" $track_no)
    echo "track${track_no_formated}.mp3"
}

convert() {
    echo "Converting tracs to mp3"
    local tmp_dir=$1
    for file in $tmp_dir/*.wav; do
        export LAST_TRACK_NO=$((LAST_TRACK_NO + 1))
        track_name=$(format_track_name $LAST_TRACK_NO)
        ffmpeg -i "$file" -codec:a libmp3lame -qscale:a 2 "$track_name"
    done
    rm -rf -- "$tmp_dir"
}

while true; do
    wait_new_cd
    tmp_dir=$(load_cd)
    convert "$tmp_dir"
done
